USE bookdb;

INSERT INTO tbl_book (title, author, price, image_url)
VALUES ('Hidden Security Principles', 'Smith Doe', 33000, '/resources/images/book_1.svg'),
       ('Modern Algorithm Principles', 'Bloch Jung', 52000, '/resources/images/book_2.svg'),
       ('Essential AI Patterns', 'Lee Jung', 38000, '/resources/images/book_3.svg'),
       ('Modern Cloud Patterns', 'Martin Jung', 48000, '/resources/images/book_4.svg'),
       ('Basic Web Design handbook', 'Doe Bloch', 95000, '/resources/images/book_5.svg'),
       ('Hidden Cloud Patterns', 'Smith Doe', 57000, '/resources/images/book_6.svg'),
       ('Modern Algorithm Patterns', 'Doe Doe', 41000, '/resources/images/book_7.svg'),
       ('Complete Java Secrets', 'Smith Park', 26000, '/resources/images/book_8.svg'),
       ('Complete Web Design Architecture', 'Kim Lee', 27000, '/resources/images/book_9.svg'),
       ('Hidden AI Mastery', 'Bloch Bloch', 79000, '/resources/images/book_10.svg'),
       ('Great Database Patterns', 'Choi Doe', 21000, '/resources/images/book_11.svg'),
       ('Essential Python Guide', 'Smith Kang', 95000, '/resources/images/book_12.svg'),
       ('Practical Security handbook', 'Martin Kim', 78000, '/resources/images/book_13.svg'),
       ('Modern Security Programming', 'Lee Bloch', 41000, '/resources/images/book_14.svg'),
       ('Professional Web Design for Beginners', 'Jung Kim', 66000, '/resources/images/book_15.svg'),
       ('Hidden Web Design Programming', 'Park Kang', 24000, '/resources/images/book_16.svg'),
       ('Introductory Java handbook', 'Lee Bloch', 70000, '/resources/images/book_17.svg'),
       ('Great Network handbook', 'Lee Park', 97000, '/resources/images/book_18.svg'),
       ('Practical Network handbook', 'Doe Jung', 81000, '/resources/images/book_19.svg'),
       ('Professional Algorithm Mastery', 'Lee Kang', 78000, '/resources/images/book_20.svg'),
       ('Basic Network Secrets', 'Doe Martin', 62000, '/resources/images/book_21.svg'),
       ('Basic Machine Learning Architecture', 'Smith Lee', 21000, '/resources/images/book_22.svg'),
       ('Professional Python handbook', 'Choi Smith', 94000, '/resources/images/book_23.svg'),
       ('Introductory Java Principles', 'Choi Lee', 37000, '/resources/images/book_24.svg'),
       ('Hidden Java Architecture', 'Jung Kim', 32000, '/resources/images/book_25.svg'),
       ('Advanced Machine Learning In Action', 'Kim Kang', 30000, '/resources/images/book_26.svg'),
       ('Professional Python for Beginners', 'Lee Park', 43000, '/resources/images/book_27.svg'),
       ('Practical Web Design for Beginners', 'Park Martin', 88000, '/resources/images/book_28.svg'),
       ('Complete Machine Learning Principles', 'Martin Kang', 23000, '/resources/images/book_29.svg'),
       ('Professional Security Mastery', 'Jung Kang', 80000, '/resources/images/book_30.svg'),
       ('Hidden AI Architecture', 'Martin Lee', 67000, '/resources/images/book_31.svg'),
       ('Complete Web Design Architecture', 'Bloch Choi', 63000, '/resources/images/book_32.svg'),
       ('Practical AI Programming', 'Jung Bloch', 48000, '/resources/images/book_33.svg'),
       ('Advanced Machine Learning Programming', 'Park Kim', 52000, '/resources/images/book_34.svg'),
       ('Essential Security Secrets', 'Martin Smith', 75000, '/resources/images/book_35.svg'),
       ('Professional Java Architecture', 'Kim Doe', 21000, '/resources/images/book_36.svg'),
       ('Modern AI handbook', 'Kang Kang', 41000, '/resources/images/book_37.svg'),
       ('Introductory Database Architecture', 'Lee Kang', 69000, '/resources/images/book_38.svg'),
       ('Basic Cloud Programming', 'Doe Choi', 23000, '/resources/images/book_39.svg'),
       ('Hidden Cloud Principles', 'Smith Bloch', 82000, '/resources/images/book_40.svg'),
       ('Practical Machine Learning Programming', 'Doe Lee', 37000, '/resources/images/book_41.svg'),
       ('Professional Algorithm Patterns', 'Jung Bloch', 75000, '/resources/images/book_42.svg'),
       ('Professional AI In Action', 'Doe Park', 26000, '/resources/images/book_43.svg'),
       ('Modern AI Principles', 'Park Smith', 47000, '/resources/images/book_44.svg'),
       ('Basic Machine Learning Principles', 'Bloch Park', 89000, '/resources/images/book_45.svg'),
       ('Professional Network for Beginners', 'Doe Lee', 62000, '/resources/images/book_46.svg'),
       ('Essential Web Design handbook', 'Choi Martin', 80000, '/resources/images/book_47.svg'),
       ('Great Cloud Guide', 'Smith Choi', 95000, '/resources/images/book_48.svg'),
       ('Complete Python Mastery', 'Bloch Park', 40000, '/resources/images/book_49.svg'),
       ('Introductory Java Mastery', 'Bloch Park', 32000, '/resources/images/book_50.svg'),
       ('Modern Python for Beginners', 'Bloch Jung', 81000, '/resources/images/book_51.svg'),
       ('Great Python for Beginners', 'Doe Bloch', 73000, '/resources/images/book_52.svg'),
       ('Complete Java Secrets', 'Lee Jung', 95000, '/resources/images/book_53.svg'),
       ('Advanced Security Principles', 'Park Kim', 21000, '/resources/images/book_54.svg'),
       ('Essential AI Guide', 'Jung Bloch', 79000, '/resources/images/book_55.svg'),
       ('Complete Machine Learning Patterns', 'Park Kim', 90000, '/resources/images/book_56.svg'),
       ('Great Machine Learning In Action', 'Smith Choi', 31000, '/resources/images/book_57.svg'),
       ('Practical Network Programming', 'Choi Smith', 62000, '/resources/images/book_58.svg'),
       ('Modern Network In Action', 'Choi Park', 52000, '/resources/images/book_59.svg'),
       ('Introductory Machine Learning Programming', 'Jung Bloch', 67000, '/resources/images/book_60.svg'),
       ('Essential Database Principles', 'Kim Smith', 42000, '/resources/images/book_61.svg'),
       ('Modern Cloud In Action', 'Choi Kim', 77000, '/resources/images/book_62.svg'),
       ('Practical Cloud Mastery', 'Martin Kang', 45000, '/resources/images/book_63.svg'),
       ('Professional Security In Action', 'Smith Kim', 55000, '/resources/images/book_64.svg'),
       ('Professional AI Guide', 'Smith Martin', 43000, '/resources/images/book_65.svg'),
       ('Hidden AI Principles', 'Park Lee', 22000, '/resources/images/book_66.svg'),
       ('Hidden Security handbook', 'Kang Martin', 22000, '/resources/images/book_67.svg'),
       ('Great Network for Beginners', 'Park Park', 71000, '/resources/images/book_68.svg'),
       ('Modern Security Principles', 'Smith Jung', 46000, '/resources/images/book_69.svg'),
       ('Hidden Java Guide', 'Martin Kang', 61000, '/resources/images/book_70.svg'),
       ('Professional Java In Action', 'Smith Lee', 24000, '/resources/images/book_71.svg'),
       ('Great Web Design In Action', 'Kang Bloch', 75000, '/resources/images/book_72.svg'),
       ('Advanced Network Patterns', 'Park Doe', 71000, '/resources/images/book_73.svg'),
       ('Hidden Security Principles', 'Smith Smith', 43000, '/resources/images/book_74.svg'),
       ('Great AI handbook', 'Doe Jung', 38000, '/resources/images/book_75.svg'),
       ('Practical Web Design Mastery', 'Kang Park', 27000, '/resources/images/book_76.svg'),
       ('Hidden Machine Learning Secrets', 'Lee Bloch', 89000, '/resources/images/book_77.svg'),
       ('Introductory Security Principles', 'Choi Smith', 42000, '/resources/images/book_78.svg'),
       ('Advanced Java for Beginners', 'Jung Park', 83000, '/resources/images/book_79.svg'),
       ('Hidden Web Design Principles', 'Park Martin', 74000, '/resources/images/book_80.svg'),
       ('Professional Java Architecture', 'Bloch Doe', 34000, '/resources/images/book_81.svg'),
       ('Practical Database In Action', 'Jung Doe', 82000, '/resources/images/book_82.svg'),
       ('Advanced Java Secrets', 'Lee Bloch', 87000, '/resources/images/book_83.svg'),
       ('Essential Network handbook', 'Smith Doe', 90000, '/resources/images/book_84.svg'),
       ('Basic Network Programming', 'Martin Kim', 79000, '/resources/images/book_85.svg'),
       ('Professional Machine Learning Secrets', 'Martin Kang', 42000, '/resources/images/book_86.svg'),
       ('Modern Web Design for Beginners', 'Choi Kang', 91000, '/resources/images/book_87.svg'),
       ('Complete Java In Action', 'Jung Choi', 21000, '/resources/images/book_88.svg'),
       ('Modern AI Secrets', 'Kim Kim', 19000, '/resources/images/book_89.svg'),
       ('Practical Algorithm for Beginners', 'Smith Kim', 64000, '/resources/images/book_90.svg'),
       ('Professional Python Architecture', 'Choi Kim', 73000, '/resources/images/book_91.svg'),
       ('Hidden Algorithm Architecture', 'Choi Lee', 80000, '/resources/images/book_92.svg'),
       ('Complete Security Secrets', 'Kim Martin', 33000, '/resources/images/book_93.svg'),
       ('Advanced Cloud Guide', 'Lee Park', 40000, '/resources/images/book_94.svg'),
       ('Complete Network Patterns', 'Kim Smith', 32000, '/resources/images/book_95.svg'),
       ('Complete Java for Beginners', 'Martin Martin', 85000, '/resources/images/book_96.svg'),
       ('Modern Security handbook', 'Doe Jung', 34000, '/resources/images/book_97.svg'),
       ('Advanced Machine Learning Programming', 'Park Kim', 46000, '/resources/images/book_98.svg'),
       ('Professional AI Architecture', 'Kim Kim', 19000, '/resources/images/book_99.svg'),
       ('Practical Database handbook', 'Park Smith', 43000, '/resources/images/book_100.svg');


